# Generated by Django 2.2.5 on 2019-12-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mytable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('branch', models.CharField(db_column='Branch', max_length=30)),
            ],
            options={
                'db_table': 'myTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('pass_field', models.CharField(db_column='pass', max_length=350)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
