# Generated by Django 2.2.5 on 2020-01-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0004_auto_20191226_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BasketTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_column='User', max_length=13)),
                ('session_id', models.CharField(db_column='Session_ID', max_length=300)),
                ('store_id', models.IntegerField(blank=True, db_column='Store_ID', null=True)),
                ('barcode', models.CharField(db_column='Barcode', max_length=20)),
                ('number_of_items', models.IntegerField(blank=True, db_column='Number_of_Items', null=True)),
                ('timestamp', models.DateTimeField(db_column='Timestamp')),
                ('mrp_per_item', models.FloatField(blank=True, db_column='MRP_per_Item', null=True)),
                ('total_mrp', models.FloatField(blank=True, db_column='Total_MRP', null=True)),
                ('retailer_price_per_item', models.FloatField(blank=True, db_column='Retailer_Price_per_Item', null=True)),
                ('total_retailer_price', models.FloatField(blank=True, db_column='Total_Retailer_Price', null=True)),
                ('our_price_per_item', models.FloatField(blank=True, db_column='Our_Price_per_Item', null=True)),
                ('discount_per_item', models.FloatField(blank=True, db_column='Discount_per_Item', null=True)),
                ('total_our_price', models.FloatField(blank=True, db_column='Total_Our_Price', null=True)),
                ('total_discount', models.FloatField(blank=True, db_column='Total_Discount', null=True)),
            ],
            options={
                'db_table': 'Basket_Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'image_upload',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceTable',
            fields=[
                ('receipt_no', models.BigAutoField(db_column='Receipt_No', primary_key=True, serialize=False, unique=True)),
                ('txn_id', models.CharField(db_column='Txn_ID', max_length=500)),
                ('order_id', models.CharField(db_column='Order_ID', max_length=500)),
                ('payment_mode', models.CharField(db_column='Payment_Mode', max_length=50)),
                ('user', models.CharField(db_column='User', max_length=13)),
                ('session_id', models.CharField(db_column='Session_ID', max_length=300)),
                ('store_id', models.IntegerField(blank=True, db_column='Store_ID', null=True)),
                ('total_mrp', models.FloatField(blank=True, db_column='Total_MRP', null=True)),
                ('total_retailers_price', models.FloatField(db_column='Total_Retailers_Price')),
                ('total_our_price', models.FloatField(db_column='Total_Our_Price')),
                ('total_discount', models.FloatField(blank=True, db_column='Total_Discount', null=True)),
                ('referral_balance_used', models.FloatField(blank=True, db_column='Referral_Balance_Used', null=True)),
                ('final_amount_paid', models.FloatField(blank=True, db_column='Final_Amount_Paid', null=True)),
                ('total_savings', models.FloatField(blank=True, db_column='Total_Savings', null=True)),
                ('timestamp', models.DateTimeField(db_column='Timestamp')),
                ('comments', models.CharField(blank=True, db_column='Comments', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Invoice_Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mytable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('branch', models.CharField(db_column='Branch', max_length=30)),
            ],
            options={
                'db_table': 'myTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDatabaseDesiFarms',
            fields=[
                ('barcode', models.CharField(db_column='Barcode', max_length=20, primary_key=True, serialize=False)),
                ('store_id', models.IntegerField(db_column='Store_ID')),
                ('brand_name', models.CharField(blank=True, db_column='Brand_Name', max_length=40, null=True)),
                ('name_of_the_product', models.CharField(blank=True, db_column='Name_of_the_Product', max_length=40, null=True)),
                ('mrp', models.FloatField(blank=True, db_column='MRP', null=True)),
                ('retailer_discount', models.FloatField(blank=True, db_column='Retailer_Discount', null=True)),
                ('retailer_price', models.FloatField(blank=True, db_column='Retailer_Price', null=True)),
                ('our_discount_percentage', models.FloatField(blank=True, db_column='Our_Discount_Percentage', null=True)),
                ('our_discount', models.FloatField(blank=True, db_column='Our_Discount', null=True)),
                ('our_price', models.FloatField(blank=True, db_column='Our_Price', null=True)),
                ('total_discount', models.FloatField(blank=True, db_column='Total_Discount', null=True)),
                ('savings_due_to_retailer', models.FloatField(blank=True, db_column='Savings_due_to_Retailer', null=True)),
                ('savings_due_to_us', models.FloatField(blank=True, db_column='Savings_Due_to_Us', null=True)),
                ('total_savings', models.FloatField(blank=True, db_column='Total_Savings', null=True)),
            ],
            options={
                'db_table': 'Product_Database_Desi_Farms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreTable',
            fields=[
                ('store_id', models.IntegerField(db_column='Store_ID', primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, db_column='Store_Name', max_length=30, null=True)),
                ('store_address', models.CharField(blank=True, db_column='Store_Address', max_length=20, null=True)),
                ('store_city', models.CharField(blank=True, db_column='Store_City', max_length=20, null=True)),
                ('pincode', models.IntegerField(blank=True, db_column='Pincode', null=True)),
                ('store_state', models.CharField(blank=True, db_column='Store_State', max_length=20, null=True)),
                ('store_country', models.CharField(blank=True, db_column='Store_Country', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Store_Table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFavourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_column='User', max_length=13)),
                ('session_id', models.CharField(db_column='Session_ID', max_length=300)),
                ('store_id', models.IntegerField(db_column='Store_ID')),
                ('barcode', models.CharField(db_column='Barcode', max_length=20)),
                ('timestamp', models.DateTimeField(db_column='Timestamp')),
                ('name_of_the_product', models.CharField(db_column='Name_of_the_Product', max_length=40)),
                ('mrp', models.FloatField(blank=True, db_column='MRP', null=True)),
                ('retailer_price', models.FloatField(blank=True, db_column='Retailer_Price', null=True)),
                ('our_discount', models.FloatField(blank=True, db_column='Our_Discount', null=True)),
                ('our_price', models.FloatField(blank=True, db_column='Our_Price', null=True)),
                ('total_discount', models.FloatField(blank=True, db_column='Total_Discount', null=True)),
            ],
            options={
                'db_table': 'user_favourites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersappProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UsersApp_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=30)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=30, null=True)),
                ('sign_up_timestamp', models.DateTimeField(db_column='Sign_Up_Timestamp')),
                ('referral_phone_number', models.CharField(blank=True, db_column='Referral_Phone_Number', max_length=20, null=True)),
                ('referral_amount_acquired', models.FloatField(blank=True, db_column='Referral_Amount_Acquired', null=True)),
                ('referral_amount_used', models.FloatField(blank=True, db_column='Referral_Amount_Used', null=True)),
                ('referral_amount_balance', models.FloatField(blank=True, db_column='Referral_Amount_Balance', null=True)),
                ('number_of_referrals', models.IntegerField(blank=True, db_column='Number_of_Referrals', null=True)),
                ('logout', models.CharField(blank=True, db_column='Logout', max_length=5, null=True)),
                ('share_button_clicks', models.IntegerField(blank=True, db_column='Share_Button_Clicks', null=True)),
            ],
            options={
                'db_table': 'User_Table',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False},
        ),
    ]
