# Generated by Django 2.2.5 on 2020-01-06 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0005_auto_20200107_0507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
