# Generated by Django 2.2.5 on 2020-01-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0006_auto_20200107_0510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersappProfile',
        ),
    ]
