# Generated by Django 2.2.5 on 2020-01-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0008_auto_20200115_1738'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='BaseApp_profile',
        ),
    ]
